# Preface {.unnumbered}

This book is a compilation of lecture notes from the MIT Course **18.337J/6.338J**: _Parallel Computing and Scientific Machine Learning_.
It is meant to be a live document, updating to continuously add the latest details on methods from the field of scientific machine learning and 
the latest techniques for high-performance computing.

All original content was created by Dr. Chris Rackauckas with assistance from David Sanders. Contributors from JuliaHub & MIT continue to make revisions in the hopes to make the SciML ecosystem accessible to all.

Examples and applications will be shown using the Julia programming langauge.

::: {.callout-note}
You can help improve this course!
Please
[report mistakes](https://github.com/SciML/SciMLBook/issues/new?assignees=&labels=bug&template=bug-report.md&title=Fix+Mistake)
you find in the content.
Similarly,
[suggest improvements](https://github.com/SciML/SciMLBook/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=New+Feature) 
on how to organize and navigate this site.
:::
